export const HOMEPAGE = '/'
export const ABOUT = '/about'
export const WORK = '/work'
export const CONTACT = '/contact'
export const CASTTOTV = '/works/cast-to-tv'
export const NETWORK = '/works/network'